### ISSUE TITLE
Update Jekyll page data

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#12]
Contributors can merge data updates into Jekyll page front matter so that the data values used by the Jekyll page can easily be updated on an ongoing basis.

**Comment by bechatman** [comment]
If I am reading this right, this one is the same thing as #15. Should we close this?

**Comment by gregoryjscott** [comment]
I think so. From what we've discussed, the data values will either 1) be declared as front matter values in the individual pages, 2) be setup as front matter defaults, or 3) be retrieved from an API end point. If that's true then we only need #15.

**Comment by bechatman** [comment]
Yeah, that sounds right to me. I will go ahead and close this.
