### ISSUE TITLE
Append custom front matter

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#14]
Contributors can append custom data to Jekyll page front matter so that categories, tags, and boolean flags can easily be associated to groups of content.

**Comment by gregoryjscott** [comment]
We may be able to use Front Matter Defaults http://jekyllrb.com/docs/configuration/#front-matter-defaults to satisfy this need.

**Comment by bechatman** [comment]
Front-matter defaults would be great, but I have always had problems getting them to work. I went ahead and made a couple commits to this branch to test on some content. As you can see, the defaults work great on pages, but you can't target sub-folders in folders with a leading underscore (_posts, _drafts, etc). I don't see that in the documentation, but that is the only thing I can see that is really different.

**Comment by gregoryjscott** [comment]
It appears that Jekyll expects a relative path (to _posts) if `type: "posts"`. The same is true for drafts.

**Comment by bechatman** [comment]
That makes more sense. Well that makes life much easier, and we can keep the changes that I made in the dataset to the City Attorney content.

**Comment by gregoryjscott** [comment]
Front matter defaults are doing the job. Closing.
