### ISSUE TITLE
Remove the need to maintain two config files

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#29]
The _config.yml and _build.yml files are almost identical. Since we're expecting to make heavy use of front matter defaults, maintaining these two config files will become a pain. There has to be a better solution.

**Comment by bechatman** [comment]
I definitely agree with you on that point, but I wasn't able to find a solution. `jekyll build` wouldn't accept custom variables as part of the command (--stage 'true' for example). The baseurl could probably be set that way, but two files was the only way I could find to pass the stage value.
