### ISSUE TITLE
Importer end_date null values

### ISSUE THREAD

**Issue by bechatman** [cityoffortworth/FortWorthTexas.gov#37]
I don't see any rendering issues, but is there a way to suppress the `end_date` output if it is blank or not included in the XML? 
I just know that there are sometimes issues if a front matter variable doesn't have a value.

**Comment by gregoryjscott** [comment]
That can be done.

**Comment by bechatman** [comment]
Just ran some tests on all the date logic, and it is working great. This seems to be the only issue, and it just made a verbose build process with all the errors popping up.
