### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#4]
Contributors can push contributions to GitHub and the CI process will handle deployment appropriately so that content updates are easy.

- [x] Setup Staging to build and deploy when commits are pushed to the `master` branch and every hour.
- [x] Setup Production to build and deploy when commits are pushed to the `master` branch and every hour.
- [x] Setup cfwroundup job
- [x] Setup cfw-datastore job

**Comment by bechatman** [comment]
For deployment purposes, there are two Jekyll config files in the repo. _config.yml is used for the staging server. For the production build, _build.yml should be used.

**Comment by gregoryjscott** [comment]
I believe Staging is good to go. It currently builds daily and on every push to the `master` branch. It is set to poll GitHub every 5 minutes for changes.

**Comment by bechatman** [comment]
I am getting 500 errors on anything that is tied to the current CMS. I'll have Mark look into it, but you are only doing a copy and replace, correct? It shouldn't be overwriting any files that aren't present in the repo?

**Comment by gregoryjscott** [comment]
Correct, it's only doing a copy and replace.

**Comment by gregoryjscott** [comment]
I updated the description to have all the tasks we completed. We have a separate issue in cfw-datastore for the SSL problem. I'm thinking this can be closed now. @bechatman re-open if you disagree.
