### ISSUE TITLE
Need to scrub items in _data for invalid characters prior to build

### ISSUE THREAD

**Issue by bechatman** [cityoffortworth/FortWorthTexas.gov#59]
Possibly a Jekyll plugin that executes prior to build?

**Comment by gregoryjscott** [comment]
There's no good reason to do this every build, it just needs to be done once and saved. This is the same reason that we didn't use a plugin for doing the data imports. I could change the Rake task to just process every file in _data and then you'd use git to see what files it affected. Not the most efficient way but you probably won't do it often (just every time you add a file to _data). It's simple. I have an idea for a fancier solution as well.

**Comment by bechatman** [comment]
So basically just make it part of the CI task that pulls from the APIs? Fancier solutions are OK, too.

**Comment by gregoryjscott** [comment]
No, I would treat it like the data imports where you run the command and check in the changes to the repository (if there are any).

I'll explain the fancier solution on our next call. I'm not sure if its a good fit for this situation or not.

**Comment by gregoryjscott** [comment]
Both content repositories now have a Rake task for scrubbing, although you have to manually change the name of the file being scrubbed in the Makefile. Additionally, I believe we decided to make use Socrata to take care of problems like this by uploading to Socrata first. I think this can be closed.
