### ISSUE TITLE
Configure Jekyll preprocessing

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#6]
Contributors can contribute SASS and JavaScript content and the content will automatically be processed appropriately so that contributors can focus on producing content and not be bothered with manually processing/deployment tasks.

**Comment by bechatman** [comment]
I think this one is a good one to put farther back on the timeline. Jekyll 2.0 introduced this capability, but since I introduced Autoprefixer to the workflow, we would need to add a plugin for that to work in the existing workflow.

**Comment by gregoryjscott** [comment]
SASS is working in the cfw-roundup repo. I don't know of any current JavaScript processing needs. I'm closing this one. We can create a new issue if/when JS processing is needed.

**Comment by bechatman** [comment]
Not sure if this warrants reopening the issue but is there a way to config autoprefixer as part of the preprocessing workflow?

**Comment by gregoryjscott** [comment]
I've never used autoprefixer. I guess open an issue for it specifically and I'll look into it.
